name: Test-workflow

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/workflow/*'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        pytchon-version: [3.8, 3.9]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        witch: 
          python-version: ${{ matrix.python-version }}
      - name: install  dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest  # Запуск тестов
  notifi:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: sdffs
        run: echo "Build completed successfully!"
  scheduled-task:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'  
    steps:
      - name: Run scheduled task
        run: echo "This task runs on a schedule!"

  manual-task:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  
    steps:
      - name: Run manual task
        run: echo "This task was triggered manually!"
      
